# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/model_worker_server',
                'doc_host': 'https://vempaliakhil96.github.io',
                'git_url': 'https://github.com/vempaliakhil96/model_worker_server',
                'lib_path': 'model_worker_server'},
  'syms': { 'model_worker_server.core': { 'model_worker_server.core.GunicornLogger': ( 'core.html#gunicornlogger',
                                                                                       'model_worker_server/core.py'),
                                          'model_worker_server.core.GunicornLogger.setup': ( 'core.html#gunicornlogger.setup',
                                                                                             'model_worker_server/core.py'),
                                          'model_worker_server.core.TerminateProtected': ( 'core.html#terminateprotected',
                                                                                           'model_worker_server/core.py'),
                                          'model_worker_server.core.TerminateProtected.__init__': ( 'core.html#terminateprotected.__init__',
                                                                                                    'model_worker_server/core.py'),
                                          'model_worker_server.core.TerminateProtected.exit_gracefully': ( 'core.html#terminateprotected.exit_gracefully',
                                                                                                           'model_worker_server/core.py')}}}
