# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/worker_model_server',
                'doc_host': 'https://vempaliakhil96.github.io',
                'git_url': 'https://github.com/vempaliakhil96/worker_model_server',
                'lib_path': 'worker_model_server'},
  'syms': {'worker_model_server.core': {'worker_model_server.core.foo': ('core.html#foo', 'worker_model_server/core.py')}}}
